name: dotted_decoration
description: Dotted line decoration is handly package to draw dotted divider, dotted border for rectangle, circle or rounded rectangle.
version: 1.0.0
homepage: https://github.com/mdalameen
author: Mohamed Al Ameen <mdalameen.s@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: